apiVersion: v1
kind: Service
metadata:
  name: service-rethinkdb
  labels:
    name: rethinkdb-statefulset
spec:
  selector:
    name: rethinkdb-statefulset
  ports:
  - port: 28015
    targetPort: 28015
    protocol: TCP