apiVersion: v1
kind: Service
metadata:
  name: service-rethinkdb-proxies
  labels:
    name: rethinkdb-replicationcontroller
spec:
  type: LoadBalancer
  ports:
  - name: admin
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: driver
    port: 28015
    targetPort: 28015
  - name: cluster
    port: 29015
    targetPort: 29015
  selector:
    name: rethinkdb-replicationcontroller
    
