apiVersion: v1
kind: Service
metadata:
  name: service-rethinkdb-proxies
  labels:
    name: rethinkdb-replicationcontroller
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: rethinkdb-replicationcontroller
    
